CREATE TABLE [dbo].[Employer]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Code] VARCHAR(3) NOT NULL,
	[Name] VARCHAR(30) NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[State] VARCHAR(30) NOT NULL,
	[Street] VARCHAR(30) NOT NULL,
	[City] VARCHAR(30) NOT NULL,
	[Zip] VARCHAR(9) NOT NULL,
	[Logo] VARCHAR(MAX) NOT NULL
)
